### ISSUE TITLE
Review of peek-poke

### ISSUE THREAD

**Issue by Gankra** [djg/peek-poke#1]
TODO:

* [x] peek-poke
* [ ] peek-poke-derive

**Comment by Gankra** [comment]
lib.rs

------------------------------


line 15:

I suggest using the pointer methods to make this code easier to read (very easy to mix up the arguments on ptr::copy):

```rust
// methods specify to/from to make direction clear
v.as_ptr().copy_to_nonoverlapping(bytes, v.len());

v.as_mut_ptr().copy_from_nonoverlapping(bytes, v.len());
```



------------------------------

line 31:

Strictly speaking `Poke` should be an unsafe trait, as misimplementing max_size leads to Undefined Behaviour, correct?

`poke_into` and `peek_from` should also be unsafe functions because they access raw pointers (which could be dangling).





------------------------------

line 79:

First off, it took me way too long to realize why this wasn't infinitely mutually recursive with the implementation for arrays. I suggest renaming the free function peek/poke methods so that they aren't as easily mistaken as recursive calls into the trait methods.

Second off, you should avoid playing with the footgun of mem::uninitialized: https://gankro.github.io/blah/initialize-me-maybe/

I recommend instead doing:

```
    fn peek_from(&mut self, bytes: *const u8) -> *const u8 {
        let int_bytes = mem::transmute::<&mut ty, &mut [u8; size_of::<$ty>()]>();
        peek_from(int_bytes, bytes)
    }
```

I see no reason why you should use the ne_bytes methods here. This also avoids any nasty issues with temporarily messing around with raw pointers. Good call on not using ptr::read/write though. That would be broken because the bytes buffer isn't known to be aligned.

You should be able to do the same thing for the float impl in case you really want to avoid semantically having another copy that the compiler needs to eliminate.


------------------------------

line 193:

This is a more legitimate but also terrifying use of mem::unintialized. I suggest using the MaybeUninit definition to do this properly (a union with an empty case so the compiler knows the memory may be uninit). Like, we should be using MaybeUninit, but it's only stable on beta right now. But it's definition is easily shimmable.

There is also an interesting question of if we should try to use:

```
#[repr(u8)]
enum COption<T> {
    None,
    Some(T),
}
```

For some of the Options in the display list. That way they can be deserialized in-place.

**Comment by Gankra** [comment]
euclid.rs ✅

**Comment by Gankra** [comment]
Hmm, further reflection on [the use of mem::uninitialized on 193 distresses me](https://github.com/djg/peek-poke/blob/master/src/lib.rs#L193). It seems distinctly not-exception-safe. And I *can* trigger a panic in this code by parsing `[1, 3, 0]` as an `Option<Option<ThingWithDestructor>>`. This is "fine" as long as this code is only ever used by webrender in gecko, since it's built with `panic=abort`, but there's non-gecko users of webrender.

You should require `T: Copy` so this can't be misused.

Also it's *possibly* busted for peek-poke to use `&mut self` for this specific case. That is a corner of the language the Unsafe Code Guidelines team hasn't agreed on.

This case was easier to handle with bincode because we could always fallback to *not* using `deserialize_in_place`.

Possibly this is a compelling reason to just *not* support `Option`, and only support `COption`?

**Comment by Gankra** [comment]
Oh and just more generally,

```
let x: T = mem::uninitialized();
let ptr = &mut x;
*ptr = ...;
```

Is fundamentally broken if `T` has a destructor, as the compiler has to assume it needs to destroy the old value to write any value (and the old value is just uninitialized memory).

If you don't want the `T: Copy` constraint you can add `assert!(!mem::needs_drop::<T>())`: https://doc.rust-lang.org/std/mem/fn.needs_drop.html

It's ultimately a static assertion so it shouldn't have any runtime affects.

**Comment by Gankra** [comment]
The maximally safe and correct implementation here is to change everything to take `*mut Self` and use ptr.copy_from/ptr.write to overwrite the value.

**Comment by Gankra** [comment]
Oh a kinda weird other alternative is to require `T: Default` here to create a default value.

**Comment by jrmuizel** [comment]
I don't think MaybeUninit is easily shimable because stable rust requires types in unions to be `Copy`. However, maybe all the types we need for WebRender are still `Copy`?

**Comment by Gankra** [comment]
Yeah I think using Default is a safer solution anyway, assuming we can do that. If we're making too big things, we can move to using COption for those cases.

**Comment by djg** [comment]
Thanks for the review @Gankro. (And MaybeUninit suggestion @jrmuizel).
I wasn't really happy with unsafe { mem::uninitialized() } but I wanted a cheap way to create the memory to hold a value before writing into it.

**Comment by djg** [comment]
> Is fundamentally broken if `T` has a destructor, as the compiler has to assume it needs to destroy the old value to write any value (and the old value is just uninitialized memory).

I kinda knew that it was dangerous and I built what was needed for WR display_list serialization which doesn't have 

> If you don't want the `T: Copy` constraint you can add `assert!(!mem::needs_drop::<T>())`: https://doc.rust-lang.org/std/mem/fn.needs_drop.html
> 
> It's ultimately a static assertion so it shouldn't have any runtime affects.

 Maybe it would be OK to add a feature to switch between `T: Copy` and `assert!(!mem::needs_drop::<T>())`?

**Comment by djg** [comment]
> lib.rs
> 
> line 15:

✅

> line 31:

✅

> line 79:
> 
> First off, it took me way too long to realize why this wasn't infinitely mutually recursive with the implementation for arrays. I suggest renaming the free function peek/poke methods so that they aren't as easily mistaken as recursive calls into the trait methods.

✅ Renamed.

> I recommend instead doing:
> 
> ```
>     fn peek_from(&mut self, bytes: *const u8) -> *const u8 {
>         let int_bytes = mem::transmute::<&mut ty, &mut [u8; size_of::<$ty>()]>();
>         peek_from(int_bytes, bytes)
>     }
> ```

✅ Resulted in removal of code. 🎉 

> line 193:
> 
> This is a more legitimate but also terrifying use of mem::unintialized. I suggest using the MaybeUninit definition to do this properly (a union with an empty case so the compiler knows the memory may be uninit). Like, we should be using MaybeUninit, but it's only stable on beta right now. But it's definition is easily shimmable.

```
    let mut __0: T = unsafe { uninitialized() };
    let bytes = __0.peek_from(bytes);
    *self = Some(__0);
```

I take it the issue isn't I use the `Some(...)` to initialize the uninitialized __0, but that if an error occurs before `*self = Some(__0);` the compiler assumes that __0 already contains a valid T, which is does not? 

> There is also an interesting question of if we should try to use:
> 
> ```
> #[repr(u8)]
> enum COption<T> {
>     None,
>     Some(T),
> }
> ```

Can you explain this a little more? I tried to understand how to write the tag separately from T, but don't we still need a placeholder to write the T into?
